### ISSUE TITLE
Server boot crash

### ISSUE THREAD

**Issue by SFort** [TwilightWingsStudio/CompositeGear#1]
Crash: [Pastebin](https://pastebin.com/KEwziHJE)
industrialcraft-2-2.8.54-ex112
CompositeGear-1.12.2-1.2
forge-1.12.2-14.23.2.2618

**Comment by zcaliptium** [comment]
Wow! My first issue. I'll check it today. )
Seems like in latest Forge version was changed some stuff.

UPDATE: Found out where is problem. I'll try to release update which fixes that issue as soon as possible.

**Comment by zcaliptium** [comment]
Released the update 1.3. Now server won't crash. Thanks for reporting. )
You can download it here from GitHub (releases section) or from CurseForge.
