### ISSUE TITLE
Unclear as to how to color armor

### ISSUE THREAD

**Issue by WrongWeekend** [TwilightWingsStudio/CompositeGear#5]
I'm trying to figure out how to color this mod's armor, which does not seem to be documented. I have tried crafting it with dyes in the inventory crafting menu and crafting table like leather armor, and by using dyes with armor on armor stands with no success.

**Comment by zcaliptium** [comment]
Hello, friend.

It should be colorable in a same way as leather armor. So you put it in crafting grid with dye. And so on.

It could be cool if you provide a little bit more data:
* Minecraft Version
* Forge Version
* Mod Version

Do you have any mods which affect crafting tables?

**Comment by WrongWeekend** [comment]
I'm running a game with only Composite Gear, no other mods.

Minecraft Version: 1.12.2

Forge Version: 1.12.2-forge1.12.2-14.23.5.2768

Mod Version: CompositeGear-1.12.2-1.6
https://minecraft.curseforge.com/projects/compositegear/files/2640308

Leather armor coloring works:
https://i.imgur.com/kl6x54d.png

Coloring the composite sword works:
https://i.imgur.com/5seAymW.png

But coloring the composite armor does not:
https://i.imgur.com/CrcqUWY.png

The composite bow and dagger cannot be colored either, but I am not sure if they are supposed to be colorable yet.

**Comment by zcaliptium** [comment]
Issue confirmed. I tested with different Forge versions.

And... For some reason this bug may happen only in release version. All recipes are working in development environment. I think I will release minor version with fixes ASAP.

Thanks for report! :)

**Comment by zcaliptium** [comment]
Fixed!
